version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          reusable: true
      - run:
          name: Install Dependencies
          command: sudo pip install awscli
      - run:
          name: Build Docker Image
          command: |
            docker build -t html2pdf:latest .
            docker run -d -it -p 127.0.0.1:8080:8080 --name html2pdf html2pdf
            docker exec html2pdf python tests.py
            sleep 30
      - deploy:
          name: Publish
          command: |
            aws ecr get-login --region us-east-1 --no-include-email | sh
            ./publish.sh
