version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          reusable: true
      - run:
          name: Install Dependencies
          command: sudo pip install requests awscli
      - run:
          name: Build Docker Image
          command: |
            docker build -t html2pdf:latest .
            docker run -d -it -p 12345:8080 --name html2pdf html2pdf
            docker create -v /cfg --name configs alpine:3.4 /bin/true
            docker cp /test.py configs:/cfg
            docker run --volumes-from configs --network container:html2pdf python tests.py
            sleep 10
      # - run:
      #     name: Run Tests
      #     command: python tests.py
      - deploy:
          name: Publish
          command: |
            aws ecr get-login --region us-east-1 --no-include-email | sh
            ./publish.sh
